name: 0.0.1.2. Lazy - Balance - With real wallet

on: 
  workflow_dispatch

jobs:
  lazy-production-real-wallet-balance-tests:
    uses: ./.github/workflows/z_Reusable_LazyNoWallet.yml
    with:
      base_url: 'https://balance.summer.fi/earn'
      script: ci:lazy-production:real-wallet:balance
      report_name: lazy-real-wallet-balance
    secrets: inherit
