name: 0.0.1. Lazy - With real wallet

on: 
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Environment base URL to run the tests on.'
        type: string
        default: 'https://staging.summer.fi'
        required: true

jobs:
  lazy-real-wallet-tests:
    uses: ./.github/workflows/z_Reusable_EarnRegressionWithRealWallet.yml
    with:
      base_url: ${{ inputs.base_url }}
      script: ci:lazy-real-wallet-regression
    secrets: inherit