name: 0. Regression - All

on: 
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Environment base URL to run the tests on.'
        type: string
        default: 'https://staging.summer.fi'
        required: true
      flags_features:
        description: 'Features Flags to enable / disable. For example: "flag1:true flag2:false"'
        type: string
        default: ''
        required: false

jobs:
  no-wallet-tests:
    name: 'No wallet'
    uses: ./.github/workflows/z_Reusable_RegressionNoWallet.yml
    with:
      base_url: ${{ inputs.base_url }}
      flags_features: ${{ inputs.flags_features}}

  with-wallet-aave-arbitrum-tests:
    name: 'With wallet - Aave - Arbitrum'
    runs-on: ubuntu-latest
    env:
      TENDERLY_PROJECT: ${{ secrets.TENDERLY_PROJECT }}
      TENDERLY_USER: ${{ secrets.TENDERLY_USER }}
      TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
    container:
      image: synthetixio/docker-node:18.16-ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Install playwright
        run: npx playwright install && npx playwright install-deps
      - name: Install xvfb
        run: apt-get update -y && apt-get -y install xvfb && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
      - name: Run With wallet Aave Arbitrum tests
        run: |
          TENDERLY_PROJECT=${{ secrets.TENDERLY_PROJECT }} \
          TENDERLY_USER=${{ secrets.TENDERLY_USER }} \
          TENDERLY_ACCESS_KEY=${{ secrets.TENDERLY_ACCESS_KEY }} \
          BASE_URL=${{ inputs.base_url }} \
          FLAGS_FEATURES=${{ inputs.flags_features}} \
          yarn ci:with-wallet:aave:arbitrum:regression
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-with-wallet-aave-arbitrum
          path: playwright-reports/with-wallet-aave-arbitrum
          retention-days: 30

  with-wallet-aave-base-tests:
    name: 'With wallet - Aave - Base'
    runs-on: ubuntu-latest
    env:
      TENDERLY_PROJECT: ${{ secrets.TENDERLY_PROJECT }}
      TENDERLY_USER: ${{ secrets.TENDERLY_USER }}
      TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
    container:
      image: synthetixio/docker-node:18.16-ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Install playwright
        run: npx playwright install && npx playwright install-deps
      - name: Install xvfb
        run: apt-get update -y && apt-get -y install xvfb && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
      - name: Run With wallet Aave Base tests
        run: |
          TENDERLY_PROJECT=${{ secrets.TENDERLY_PROJECT }} \
          TENDERLY_USER=${{ secrets.TENDERLY_USER }} \
          TENDERLY_ACCESS_KEY=${{ secrets.TENDERLY_ACCESS_KEY }} \
          BASE_URL=${{ inputs.base_url }} \
          FLAGS_FEATURES=${{ inputs.flags_features}} \
          yarn ci:with-wallet:aave:base:regression
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-with-wallet-aave-base
          path: playwright-reports/with-wallet-aave-base
          retention-days: 30

  with-wallet-aave-ethereum-tests:
    name: 'With wallet - Aave - Ethereum'
    runs-on: ubuntu-latest
    env:
      TENDERLY_PROJECT: ${{ secrets.TENDERLY_PROJECT }}
      TENDERLY_USER: ${{ secrets.TENDERLY_USER }}
      TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
    container:
      image: synthetixio/docker-node:18.16-ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Install playwright
        run: npx playwright install && npx playwright install-deps
      - name: Install xvfb
        run: apt-get update -y && apt-get -y install xvfb && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
      - name: Run With wallet Aave Ethereum tests
        run: |
          TENDERLY_PROJECT=${{ secrets.TENDERLY_PROJECT }} \
          TENDERLY_USER=${{ secrets.TENDERLY_USER }} \
          TENDERLY_ACCESS_KEY=${{ secrets.TENDERLY_ACCESS_KEY }} \
          BASE_URL=${{ inputs.base_url }} \
          FLAGS_FEATURES=${{ inputs.flags_features}} \
          yarn ci:with-wallet:aave:ethereum:regression
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-with-wallet-aave-ethereum
          path: playwright-reports/with-wallet-aave-ethereum
          retention-days: 30

  with-wallet-aave-optimism-tests:
    name: 'With wallet - Aave - Optimism'
    runs-on: ubuntu-latest
    env:
      TENDERLY_PROJECT: ${{ secrets.TENDERLY_PROJECT }}
      TENDERLY_USER: ${{ secrets.TENDERLY_USER }}
      TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
    container:
      image: synthetixio/docker-node:18.16-ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Install playwright
        run: npx playwright install && npx playwright install-deps
      - name: Install xvfb
        run: apt-get update -y && apt-get -y install xvfb && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
      - name: Run With wallet Aave Optimism tests
        run: |
          TENDERLY_PROJECT=${{ secrets.TENDERLY_PROJECT }} \
          TENDERLY_USER=${{ secrets.TENDERLY_USER }} \
          TENDERLY_ACCESS_KEY=${{ secrets.TENDERLY_ACCESS_KEY }} \
          BASE_URL=${{ inputs.base_url }} \
          FLAGS_FEATURES=${{ inputs.flags_features}} \
          yarn ci:with-wallet:aave:optimism:regression
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-with-wallet-aave-optimism
          path: playwright-reports/with-wallet-aave-optimism
          retention-days: 30

  with-wallet-ajna-arbitrum-tests:
    name: 'With wallet - Ajna - Arbitrum'
    runs-on: ubuntu-latest
    env:
      TENDERLY_PROJECT: ${{ secrets.TENDERLY_PROJECT }}
      TENDERLY_USER: ${{ secrets.TENDERLY_USER }}
      TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
    container:
      image: synthetixio/docker-node:18.16-ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Install playwright
        run: npx playwright install && npx playwright install-deps
      - name: Install xvfb
        run: apt-get update -y && apt-get -y install xvfb && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
      - name: Run With wallet Ajna Arbitrum
        run: |
          TENDERLY_PROJECT=${{ secrets.TENDERLY_PROJECT }} \
          TENDERLY_USER=${{ secrets.TENDERLY_USER }} \
          TENDERLY_ACCESS_KEY=${{ secrets.TENDERLY_ACCESS_KEY }} \
          BASE_URL=${{ inputs.base_url }} \
          FLAGS_FEATURES=${{ inputs.flags_features}} \
          yarn ci:with-wallet:ajna:arbitrum:regression
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-with-wallet-ajna-arbitrum
          path: playwright-reports/with-wallet-ajna-arbitrum
          retention-days: 30

  with-wallet-ajna-base-tests:
    name: 'With wallet - Ajna - Base'
    runs-on: ubuntu-latest
    env:
      TENDERLY_PROJECT: ${{ secrets.TENDERLY_PROJECT }}
      TENDERLY_USER: ${{ secrets.TENDERLY_USER }}
      TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
    container:
      image: synthetixio/docker-node:18.16-ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Install playwright
        run: npx playwright install && npx playwright install-deps
      - name: Install xvfb
        run: apt-get update -y && apt-get -y install xvfb && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
      - name: Run With wallet Ajna Base
        run: |
          TENDERLY_PROJECT=${{ secrets.TENDERLY_PROJECT }} \
          TENDERLY_USER=${{ secrets.TENDERLY_USER }} \
          TENDERLY_ACCESS_KEY=${{ secrets.TENDERLY_ACCESS_KEY }} \
          BASE_URL=${{ inputs.base_url }} \
          FLAGS_FEATURES=${{ inputs.flags_features}} \
          yarn ci:with-wallet:ajna:base:regression
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-with-wallet-ajna-base
          path: playwright-reports/with-wallet-ajna-base
          retention-days: 30

  with-wallet-ajna-ethereum-tests:
    name: 'With wallet - Ajna - Ethereum'
    runs-on: ubuntu-latest
    env:
      TENDERLY_PROJECT: ${{ secrets.TENDERLY_PROJECT }}
      TENDERLY_USER: ${{ secrets.TENDERLY_USER }}
      TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
    container:
      image: synthetixio/docker-node:18.16-ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Install playwright
        run: npx playwright install && npx playwright install-deps
      - name: Install xvfb
        run: apt-get update -y && apt-get -y install xvfb && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
      - name: Run With wallet Ajna Ethereum
        run: |
          TENDERLY_PROJECT=${{ secrets.TENDERLY_PROJECT }} \
          TENDERLY_USER=${{ secrets.TENDERLY_USER }} \
          TENDERLY_ACCESS_KEY=${{ secrets.TENDERLY_ACCESS_KEY }} \
          BASE_URL=${{ inputs.base_url }} \
          FLAGS_FEATURES=${{ inputs.flags_features}} \
          yarn ci:with-wallet:ajna:ethereum:regression
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-with-wallet-ajna-ethereum
          path: playwright-reports/with-wallet-ajna-ethereum
          retention-days: 30

  with-wallet-ajna-optimism-tests:
    name: 'With wallet - Ajna - Optimism'
    runs-on: ubuntu-latest
    env:
      TENDERLY_PROJECT: ${{ secrets.TENDERLY_PROJECT }}
      TENDERLY_USER: ${{ secrets.TENDERLY_USER }}
      TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
    container:
      image: synthetixio/docker-node:18.16-ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Install playwright
        run: npx playwright install && npx playwright install-deps
      - name: Install xvfb
        run: apt-get update -y && apt-get -y install xvfb && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
      - name: Run With wallet Ajna Optimism
        run: |
          TENDERLY_PROJECT=${{ secrets.TENDERLY_PROJECT }} \
          TENDERLY_USER=${{ secrets.TENDERLY_USER }} \
          TENDERLY_ACCESS_KEY=${{ secrets.TENDERLY_ACCESS_KEY }} \
          BASE_URL=${{ inputs.base_url }} \
          FLAGS_FEATURES=${{ inputs.flags_features}} \
          yarn ci:with-wallet:ajna:optimism:regression
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-with-wallet-ajna-optimism
          path: playwright-reports/with-wallet-ajna-optimism
          retention-days: 30

  with-wallet-maker-tests:
    name: 'With wallet - Maker'
    runs-on: ubuntu-latest
    env:
      TENDERLY_PROJECT: ${{ secrets.TENDERLY_PROJECT }}
      TENDERLY_USER: ${{ secrets.TENDERLY_USER }}
      TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
    container:
      image: synthetixio/docker-node:18.16-ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Install playwright
        run: npx playwright install && npx playwright install-deps
      - name: Install xvfb
        run: apt-get update -y && apt-get -y install xvfb && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
      - name: Run With wallet Maker tests
        run: |
          TENDERLY_PROJECT=${{ secrets.TENDERLY_PROJECT }} \
          TENDERLY_USER=${{ secrets.TENDERLY_USER }} \
          TENDERLY_ACCESS_KEY=${{ secrets.TENDERLY_ACCESS_KEY }} \
          BASE_URL=${{ inputs.base_url }} \
          FLAGS_FEATURES=${{ inputs.flags_features}} \
          yarn ci:with-wallet:maker:regression
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-with-wallet-maker
          path: playwright-reports/with-wallet-maker
          retention-days: 30

  with-wallet-morphoblue-tests:
    name: 'With wallet - Morpho Blue'
    runs-on: ubuntu-latest
    env:
      TENDERLY_PROJECT: ${{ secrets.TENDERLY_PROJECT }}
      TENDERLY_USER: ${{ secrets.TENDERLY_USER }}
      TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
    container:
      image: synthetixio/docker-node:18.16-ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Install playwright
        run: npx playwright install && npx playwright install-deps
      - name: Install xvfb
        run: apt-get update -y && apt-get -y install xvfb && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
      - name: Run With wallet Morpho Blue tests
        run: |
          TENDERLY_PROJECT=${{ secrets.TENDERLY_PROJECT }} \
          TENDERLY_USER=${{ secrets.TENDERLY_USER }} \
          TENDERLY_ACCESS_KEY=${{ secrets.TENDERLY_ACCESS_KEY }} \
          BASE_URL=${{ inputs.base_url }} \
          FLAGS_FEATURES=${{ inputs.flags_features}} \
          yarn ci:with-wallet:morphoblue:regression
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-with-wallet-morphoblue
          path: playwright-reports/with-wallet-morphoblue
          retention-days: 30

  with-wallet-spark-tests:
    name: 'With wallet - Spark'
    runs-on: ubuntu-latest
    env:
      TENDERLY_PROJECT: ${{ secrets.TENDERLY_PROJECT }}
      TENDERLY_USER: ${{ secrets.TENDERLY_USER }}
      TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
    container:
      image: synthetixio/docker-node:18.16-ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Install playwright
        run: npx playwright install && npx playwright install-deps
      - name: Install xvfb
        run: apt-get update -y && apt-get -y install xvfb && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
      - name: Run With wallet Spark tests
        run: |
          TENDERLY_PROJECT=${{ secrets.TENDERLY_PROJECT }} \
          TENDERLY_USER=${{ secrets.TENDERLY_USER }} \
          TENDERLY_ACCESS_KEY=${{ secrets.TENDERLY_ACCESS_KEY }} \
          BASE_URL=${{ inputs.base_url }} \
          FLAGS_FEATURES=${{ inputs.flags_features}} \
          yarn ci:with-wallet:spark:regression
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-with-wallet-spark
          path: playwright-reports/with-wallet-spark
          retention-days: 30
