name: 0. Regression - All

on: 
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Environment base URL to run the tests on.'
        type: string
        default: 'https://staging.summer.fi'
        required: true
      flags_features:
        description: 'Features Flags to enable / disable. For example: "flag1:true flag2:false"'
        type: string
        default: ''
        required: false

jobs:
  no-wallet-tests:
    uses: ./.github/workflows/z_Reusable_RegressionNoWallet.yml
    with:
      base_url: ${{ inputs.base_url }}
      flags_features: ${{ inputs.flags_features}}

  with-wallet-aave-arbitrum-tests:
    uses: ./.github/workflows/z_Reusable_RegressionAaveArbitrum.yml
    with:
      base_url: ${{ inputs.base_url }}
      flags_features: ${{ inputs.flags_features}}
    secrets: inherit

  with-wallet-aave-base-tests:
    uses: ./.github/workflows/z_Reusable_RegressionAaveBase.yml
    with:
      base_url: ${{ inputs.base_url }}
      flags_features: ${{ inputs.flags_features}}
    secrets: inherit

  with-wallet-aave-ethereum-tests:
    uses: ./.github/workflows/z_Reusable_RegressionAaveEthereum.yml
    with:
      base_url: ${{ inputs.base_url }}
      flags_features: ${{ inputs.flags_features}}
    secrets: inherit

  with-wallet-aave-optimism-tests:
    uses: ./.github/workflows/z_Reusable_RegressionAaveOptimism.yml
    with:
      base_url: ${{ inputs.base_url }}
      flags_features: ${{ inputs.flags_features}}
    secrets: inherit

  with-wallet-ajna-arbitrum-tests:
    uses: ./.github/workflows/z_Reusable_RegressionAjnaArbitrum.yml
    with:
      base_url: ${{ inputs.base_url }}
      flags_features: ${{ inputs.flags_features}}
    secrets: inherit

  with-wallet-ajna-base-tests:
    uses: ./.github/workflows/z_Reusable_RegressionAjnaBase.yml
    with:
      base_url: ${{ inputs.base_url }}
      flags_features: ${{ inputs.flags_features}}
    secrets: inherit

  with-wallet-ajna-ethereum-tests:
    uses: ./.github/workflows/z_Reusable_RegressionAjnaEthereum.yml
    with:
      base_url: ${{ inputs.base_url }}
      flags_features: ${{ inputs.flags_features}}
    secrets: inherit

  with-wallet-ajna-optimism-tests:
    uses: ./.github/workflows/z_Reusable_RegressionAjnaOptimism.yml
    with:
      base_url: ${{ inputs.base_url }}
      flags_features: ${{ inputs.flags_features}}
    secrets: inherit

  with-wallet-maker-tests:
    uses: ./.github/workflows/z_Reusable_RegressionMaker.yml
    with:
      base_url: ${{ inputs.base_url }}
      flags_features: ${{ inputs.flags_features}}
    secrets: inherit

  with-wallet-morphoblue-tests:
    uses: ./.github/workflows/z_Reusable_RegressionMorphoBlue.yml
    with:
      base_url: ${{ inputs.base_url }}
      flags_features: ${{ inputs.flags_features}}
    secrets: inherit

  with-wallet-spark-tests:
    uses: ./.github/workflows/z_Reusable_RegressionSpark.yml
    with:
      base_url: ${{ inputs.base_url }}
      flags_features: ${{ inputs.flags_features}}
    secrets: inherit
