name: 0.1. Regression - Aave Ethereum

on: 
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Environment base URL to run the tests on.'
        type: string
        default: 'https://staging.summer.fi'
        required: true
      flags_features:
        description: 'Features Flags to enable / disable. For example: "flag1:true flag2:false"'
        type: string
        default: ''
        required: false

jobs:
  uses: ./.github/workflows/z_Reusable_RegressionWithWallet.yml
    with:
      protocol: aave
      network: ethereum
      base_url: ${{ inputs.base_url }}
      flags_features: ${{ inputs.flags_features}}
    secrets: inherit
