name: 1.1. Swap - Spark

on: 
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Environment base URL to run the tests on.'
        type: string
        # default: 'https://prodev.oasisapp.dev' // SWAP not working on staging
        default: 'https://summer.fi'
        required: true
      flags_features:
        description: 'Features Flags to enable / disable. For example: "flag1:true flag2:false"'
        type: string
        default: ''
        required: false

jobs:
  swap-spark-tests:
    uses: ./.github/workflows/z_Reusable_Swap.yml
    with:
      protocol: spark
      base_url: ${{ inputs.base_url }}
      flags_features: ${{ inputs.flags_features}}
    secrets: inherit
