name: Testing workflow outputs

on: 
  workflow_run:
    workflows: [API tests - OUTPUTS]
    types: [completed]

jobs:
  job_3:
    name: Display results
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v4
        with:
          name: nombre_de_paco
      - name: Print the final result
        shell: bash
        run: |
          value=`cat mi_nombre.txt`
          echo El nombre es $value
  tests-result:
    runs-on: ubuntu-latest
    steps:
      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
        run: echo "The selected color is $SELECTED_COLOR"
      - name: Get color DOS
        env:
          SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
        run: echo "The selected color is $SELECTED_COLOR"
      - run: echo '${{ github.event.workflow_run.outputs.SELECTED_COLOR }} -- CI E2E tests result -- ${{ github.event.workflow_run.conclusion }}'
      