name: API tests - OUTPUTS

on: 
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Environment base URL to run the tests on.'
        type: string
        default: 'https://staging.summer.fi'
        required: true
    outputs:
      persona: # Define the output name
        description: 'El nombre de una persona'
        value: PACO

jobs:
  job_2:
    name: Una palabra
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: echo "SOY_PACO" > mi_nombre.txt
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v4
        with:
          name: nombre_de_paco
          path: mi_nombre.txt