name: API tests - OUTPUTS

on: 
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Environment base URL to run the tests on.'
        type: string
        default: 'https://staging.summer.fi'
        required: true
      repository:
        description: 'Repository name that triggered the tests.'
        type: string
        default: '${{ github.event.workflow_dispatch.repository.name }}'
        required: true
    outputs:
      persona: # Define the output name
        description: 'El nombre de una persona'
        value: PACO

jobs:
  # sending-output:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: my-output
  #         path: output.txt
  #         retention-days: 2
  testing-outputs:
    runs-on: ubuntu-latest
    # outputs:
    #   trigger_repository: JUANJO 
    # outputs:
    #   animal: # Define the output name
    #     description: 'Es un animal'
    #     value: Gato
    steps:
      - run: echo "Testing workflow outputs"
      - name: Set muebles
        id: vars
        shell: bash
        run: |
          echo "::set-output name=mueble::silla"
      - name: Set color
        id: color-selector
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: Set output
        run: echo "::set-output name=planta::arbol"
      

