name: API tests - OUTPUTS

on: 
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Environment base URL to run the tests on.'
        type: string
        default: 'https://staging.summer.fi'
        required: true
    outputs:
      persona: # Define the output name
        description: 'El nombre de una persona'
        value: PACO

jobs:
  # sending-output:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: my-output
  #         path: output.txt
  #         retention-days: 2
  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v4
        with:
          name: homework_pre
          path: math-homework.txt
  job_2:
    name: Una palabra
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: echo "SOY_PACO" > mi_nombre.txt
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v4
        with:
          name: nombre_de_paco
          path: mi_nombre.txt
          # github-token: ${{ secrets.E2E_TESTS_PAT }}
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
  testing-outputs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing workflow outputs"
      - name: Set muebles
        id: vars
        shell: bash
        run: |
          echo "::set-output name=mueble::silla"
      - name: Set color
        id: color-selector
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: Set output
        run: echo "::set-output name=planta::arbol"
      

