name: API tests - OUTPUTS - Triggered

on: 
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run_id from respository that is triggering this workflow.'
        type: string
        required: true
      repository:
        description: 'Name of the respository that is triggering this workflow.'
        type: string
        required: true

jobs:
  staging-deployed-trigger-received:
    runs-on: ubuntu-latest 
    steps:
      - run: echo "Regression E2E and API tests for ${{ inputs.repository }} - RUN_ID ${{ inputs.run_id }}"
      - run: echo "${{ inputs.repository }}" > trigger_repository.txt
      - name: Upload trigger repository name
        uses: actions/upload-artifact@v4
        with:
          name: trigger_repository_name
          path: trigger_repository.txt
  job_2:
    name: Something else
    runs-on: ubuntu-latest
    steps:
      - run: echo "Something else running"
  job_3:
    name: Something something else
    runs-on: ubuntu-latest
    steps:
      - run: echo "Something something else running"
