name: CI E2E tests

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Testing inputs from dispatch event - NAME'
        type: string
        required: true

jobs:
  ci-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: CI - Regression E2E tests - ${{ inputs.name }}
        run: echo "Event received - NAME is ${{ inputs.name }}"