name: CI E2E tests

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Testing inputs from dispatch event - NAME'
        type: string
        required: true

jobs:
  log-${{ inputs.name }}:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Event received
        run: echo "Event received - NAME is ${{ inputs.name }}"