name: CI E2E and API tests

on: 
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run_id from respository that is triggering this workflow.'
        type: string
        required: true

jobs:
  staging-deployed-trigger-received:
    runs-on: ubuntu-latest
    outputs:
      trigger_repository: ${{ github.event.workflow_dispatch.repository.name }} 
    steps:
      - run: echo "Regression E2E and API tests for ${{ github.event.workflow_dispatch.repository.name }} - RUN_ID ${{ inputs.run_id }}"
  no-wallet-tests:
    uses: ./.github/workflows/z_Reusable_RegressionNoWallet.yml
    with:
      base_url: 'https://staging.summer.fi'
      script: ci:no-wallet:regression
  api-tests:
    uses: ./.github/workflows/z_Reusable_Apis.yml
    with:
      base_url: 'https://staging.summer.fi'
      script: api-tests:regression