name: Sending CI E2E tests result to trigger repository

on: 
  workflow_run:
    workflows: [CI E2E and API tests]
    types: [completed]

jobs:
  tests-result:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ github.event.workflow_run.repository.name }} -- CI E2E tests result -- ${{ github.event.workflow_run.conclusion }}'
      - name: Triggering E2E tests result workflow in ${{ github.event.workflow_run.repository.name }} repository
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.E2E_TESTS_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/OasisDEX/${{ github.event.workflow_run.repository.name }}/actions/workflows/e2e-tests-result.yaml/dispatches \
            -d "{\"ref\":\"dev\", \"inputs\":{\"tests_run_id\":\"${{ github.event.workflow_run.id }}\", \"tests_result\":\"${{ github.event.workflow_run.conclusion }}\"}}"