name: CI E2E tests

on: 
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run_id from oasis-borrow run that is triggering this workflow.'
        type: string
        required: true

jobs:
  ci-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: CI - Regression E2E tests for RUN_ID ${{ inputs.run_id }}
        run: echo "Event received - RUN_ID is ${{ inputs.run_id }}"