name: CI Lazy Protocol Prod Release E2E tests


on: 
  workflow_run:
    branches: [main]
    workflows: [Lazy Prod trigger]
    types: [completed]

jobs:
  # lazy-prod-release-trigger-received:
  #   runs-on: ubuntu-latest 
  #   steps:
  #     - run: echo "Regression E2E tests for ${{ inputs.repository }} - Release Earn apps workflow -  RUN_ID ${{ inputs.run_id }}"
  #     - name: Create artifact with trigger repository name
  #       run: echo "${{ inputs.repository }}" > trigger_repository.txt
  #     - name: Upload artifact with trigger repository name
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: trigger_repository_name
  #         path: trigger_repository.txt

  lazy-prod-no-wallet-tests:
    uses: ./.github/workflows/z_Reusable_LazyNoWallet.yml
    with:
      base_url: 'https://summer.fi/earn'
      script: ci:lazy-production:no-wallet
    secrets: inherit

  lazy-prod-real-wallet-tests:
    uses: ./.github/workflows/z_Reusable_LazyWithRealWallet.yml
    with:
      base_url: 'https://summer.fi/earn'
      script: ci:lazy-production:real-wallet
    secrets: inherit
