name: Lazy Prod trigger

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run_id from respository that is triggering this workflow.'
        type: string
        required: true
      repository:
        description: 'Name of the respository that is triggering this workflow.'
        type: string
        required: true
      triggerManually:
        description: 'Triggered manually'
        type: boolean
        default: false

jobs:
  lazy-prod-release-trigger-immediately:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Regression E2E tests on Production - Tests triggered manually"

  lazy-prod-release-trigger-received:
    runs-on: ubuntu-latest
    if: ${{ inputs.triggerManually == 'false'}}
    steps:
      - run: echo "Regression E2E tests for ${{ inputs.repository }} - Release Earn apps workflow -  RUN_ID ${{ inputs.run_id }}"
      - name: Create artifact with trigger repository name
        run: echo "${{ inputs.repository }}" > trigger_repository.txt
      - name: Upload artifact with trigger repository name
        uses: actions/upload-artifact@v6
        with:
          name: trigger_repository_name
          path: trigger_repository.txt

  build:
    runs-on: ubuntu-latest
    name: wait-job
    if: ${{ inputs.triggerManually == 'false'}}
    steps:
      - name: Sleep for 900 seconds
        run: sleep 900s
        shell: bash
