name: Create fork and add funds to wallet

on: 
  workflow_dispatch:
    inputs:
      network:
        description: 'Which network do you want to fork?'
        type: string
        default: 'mainnet'
        required: true
      wallet:
        description: 'Which wallet do you want to add funds to?'
        type: string
        default: ''
        required: true

jobs:
  create-for-with-funds:
    name: 'Create fork and add funds'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install TypeScript and ts-node
        run: npm install typescript ts-node
      - name: Install dependencies
        run: yarn
      - name: Run create-fork-github
        run: |
          TENDERLY_PROJECT=${{ secrets.TENDERLY_PROJECT }} \
          TENDERLY_USER=${{ secrets.TENDERLY_USER }} \
          TENDERLY_ACCESS_KEY=${{ secrets.TENDERLY_ACCESS_KEY }} \
          NETWORK=${{ inputs.network }} \
          WALLET_ADDRESS=${{ inputs.wallet}} \
          yarn create-fork-github
