name: Nightly Run

on: 
  schedule:
    - cron:  '0 1 * * 1-5'

jobs:
  no-wallet-tests:
    name: 'No wallet'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.37.1-jammy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Run NO-WALLET tests
        run: yarn nightly:no-wallet
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-no-wallet
          path: playwright-reports/no-wallet
          retention-days: 30
  with-wallet-aave-ethereum-tests:
    name: 'With wallet - Aave - Ethereum'
    runs-on: ubuntu-latest
    env:
      WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
      TENDERLY_PROJECT: ${{ secrets.TENDERLY_PROJECT }}
      TENDERLY_USER: ${{ secrets.TENDERLY_USER }}
      TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
    container:
      image: synthetixio/docker-node:18.16-ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Install playwright
        run: npx playwright install && npx playwright install-deps
      - name: Install xvfb
        run: apt-get update -y && apt-get -y install xvfb && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
      - name: Run With wallet Aave Ethereum tests
        run: |
          WALLET_ADDRESS=${{ secrets.WALLET_ADDRESS }} \
          TENDERLY_PROJECT=${{ secrets.TENDERLY_PROJECT }} \
          TENDERLY_USER=${{ secrets.TENDERLY_USER }} \
          TENDERLY_ACCESS_KEY=${{ secrets.TENDERLY_ACCESS_KEY }} \
          yarn nightly:with-wallet:aave:ethereum
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-with-wallet-aave-ethereum
          path: playwright-reports/with-wallet-aave-ethereum
          retention-days: 30
  with-wallet-aave-aother-tests:
    name: 'With wallet - Aave - Arbitrum, Optimism & Base'
    runs-on: ubuntu-latest
    env:
      WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
      TENDERLY_PROJECT: ${{ secrets.TENDERLY_PROJECT }}
      TENDERLY_USER: ${{ secrets.TENDERLY_USER }}
      TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
    container:
      image: synthetixio/docker-node:18.16-ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Install playwright
        run: npx playwright install && npx playwright install-deps
      - name: Install xvfb
        run: apt-get update -y && apt-get -y install xvfb && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
      - name: Run With wallet Aave Arbitrum, Optimism and Base tests
        run: |
          WALLET_ADDRESS=${{ secrets.WALLET_ADDRESS }} \
          TENDERLY_PROJECT=${{ secrets.TENDERLY_PROJECT }} \
          TENDERLY_USER=${{ secrets.TENDERLY_USER }} \
          TENDERLY_ACCESS_KEY=${{ secrets.TENDERLY_ACCESS_KEY }} \
          yarn nightly:with-wallet:aave:other
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-with-wallet-aave-other
          path: playwright-reports/with-wallet-aave-other
          retention-days: 30
  with-wallet-maker-and-spark-tests:
    name: 'With wallet - Maker & Spark'
    runs-on: ubuntu-latest
    env:
      WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
      TENDERLY_PROJECT: ${{ secrets.TENDERLY_PROJECT }}
      TENDERLY_USER: ${{ secrets.TENDERLY_USER }}
      TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
    container:
      image: synthetixio/docker-node:18.16-ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Install playwright
        run: npx playwright install && npx playwright install-deps
      - name: Install xvfb
        run: apt-get update -y && apt-get -y install xvfb && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
      - name: Run With wallet Maker and Spark tests
        run: |
          WALLET_ADDRESS=${{ secrets.WALLET_ADDRESS }} \
          TENDERLY_PROJECT=${{ secrets.TENDERLY_PROJECT }} \
          TENDERLY_USER=${{ secrets.TENDERLY_USER }} \
          TENDERLY_ACCESS_KEY=${{ secrets.TENDERLY_ACCESS_KEY }} \
          yarn nightly:with-wallet:maker-and-spark
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-with-wallet-maker-and-spark
          path: playwright-reports/with-wallet-maker-and-spark
          retention-days: 30