name: Playwright Tests

on: 
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Environment base URL to run the tests on.'
        type: string
        required: true

jobs:
  no-wallet-tests:
    name: 'No-wallet tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.37.1-jammy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Run NO-WALLET tests
        run: BASE_URL=${{ inputs.base_url }} yarn test:e2e:no-wallet:regression:ci
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-no-wallet
          path: playwright-reports/no-wallet
          retention-days: 30
  with-wallet-tests-aave:
    name: 'With-wallet tests - Aave'
    runs-on: ubuntu-latest
    env:
      WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
      TENDERLY_PROJECT: ${{ secrets.TENDERLY_PROJECT }}
      TENDERLY_USER: ${{ secrets.TENDERLY_USER }}
      TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
    container:
      image: synthetixio/docker-node:18.16-ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Install playwright
        run: npx playwright install && npx playwright install-deps
      - name: Install xvfb
        run: apt-get update -y && apt-get -y install xvfb && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
      - name: Run WITH-WALLET tests - Aave
        run: |
          WALLET_ADDRESS=${{ secrets.WALLET_ADDRESS }} \
          TENDERLY_PROJECT=${{ secrets.TENDERLY_PROJECT }} \
          TENDERLY_USER=${{ secrets.TENDERLY_USER }} \
          TENDERLY_ACCESS_KEY=${{ secrets.TENDERLY_ACCESS_KEY }} \
          BASE_URL=${{ inputs.base_url }} \
          yarn test:e2e:with-wallet:aave:regression:ci
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-with-wallet-aave
          path: playwright-reports/with-wallet-aave
          retention-days: 30
  with-wallet-tests-other:
    name: 'With-wallet tests - Other'
    runs-on: ubuntu-latest
    env:
      WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
      TENDERLY_PROJECT: ${{ secrets.TENDERLY_PROJECT }}
      TENDERLY_USER: ${{ secrets.TENDERLY_USER }}
      TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
    container:
      image: synthetixio/docker-node:18.16-ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Install playwright
        run: npx playwright install && npx playwright install-deps
      - name: Install xvfb
        run: apt-get update -y && apt-get -y install xvfb && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
      - name: Run WITH-WALLET tests - Other
        run: |
          WALLET_ADDRESS=${{ secrets.WALLET_ADDRESS }} \
          TENDERLY_PROJECT=${{ secrets.TENDERLY_PROJECT }} \
          TENDERLY_USER=${{ secrets.TENDERLY_USER }} \
          TENDERLY_ACCESS_KEY=${{ secrets.TENDERLY_ACCESS_KEY }} \
          BASE_URL=${{ inputs.base_url }} \
          yarn test:e2e:with-wallet:other:regression:ci
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-with-wallet-other
          path: playwright-reports/with-wallet-other
          retention-days: 30