name: Portfolio - Staging vs Production

on: 
  workflow_dispatch:
    inputs:
      flags_features:
        description: 'Features Flags to enable / disable. For example: "flag1:true flag2:false"'
        type: string
        default: ''
        required: false

jobs:
  no-wallet-tests-2:
    name: 'Portfolio - Staging vs Production - TEST'
    uses: ./.github/workflows/z_Reusable_RegressionNoWallet.yml
    with:
      base_url: ${{ inputs.base_url }}
      flags_features: ${{ inputs.flags_features}}
      script: portfolio:staging-vs-production

  no-wallet-tests:
    name: 'Portfolio - Staging vs Production'
    runs-on: ubuntu-24.04
    container:
      image: mcr.microsoft.com/playwright:v1.49.0-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Run NO-WALLET tests
        run: FLAGS_FEATURES=${{ inputs.flags_features}} yarn portfolio:staging-vs-production
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-no-wallet-portfolio
          path: playwright-reports/no-wallet-portfolio
          retention-days: 30
