name: Refinance

on: 
  schedule:
    - cron:  '0 1 * * 1-5'

jobs:
  with-wallet-refinance:
    name: 'With wallet - Refinance'
    runs-on: ubuntu-latest
    env:
      TENDERLY_PROJECT: ${{ secrets.TENDERLY_PROJECT }}
      TENDERLY_USER: ${{ secrets.TENDERLY_USER }}
      TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
    container:
      image: synthetixio/docker-node:18.16-ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Install playwright
        run: npx playwright install && npx playwright install-deps
      - name: Install xvfb
        run: apt-get update -y && apt-get -y install xvfb && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
      - name: Run With wallet Aave Ethereum tests
        run: |
          TENDERLY_PROJECT=${{ secrets.TENDERLY_PROJECT }} \
          TENDERLY_USER=${{ secrets.TENDERLY_USER }} \
          TENDERLY_ACCESS_KEY=${{ secrets.TENDERLY_ACCESS_KEY }} \
          yarn ci:with-wallet:refinance
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-with-wallet-refinance
          path: playwright-reports/with-wallet-refinance
          retention-days: 30
  