name: Reusable Workflow - Earn protocol - Regression - With real wallet tests

on: 
  workflow_call:
    inputs:
      base_url:
        description: 'Environment base URL to run the tests on.'
        type: string
        default: 'https://staging.summer.fi'
        required: false

jobs:
  with-real-wallet-tests:
    name: 'Earn - Tests with real wallet'
    runs-on: ubuntu-24.04
    container:
      image: synthetixio/docker-node:18.16-ubuntu
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Install playwright
        run: npx playwright install && npx playwright install-deps
      - name: Install xvfb
        run: apt-get update -y && apt-get -y install xvfb && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
      - name: Verify that staging environment is ready for testing
        if: ${{ inputs.base_url == 'https://staging.summer.fi' }}
        run: xvfb-run yarn verify-staging
      - name: Build Synpress cache
        run: |
          BASE_URL=${{ inputs.base_url }} \
          VERY_OLD_TEST_WALLET_PK=${{ secrets.VERY_OLD_TEST_WALLET_PK }} \
          yarn ci:synpress-build-cache:real-wallet
      - name: Run 'With real wallet' tests
        run: |
          BASE_URL=${{ inputs.base_url }} \
          yarn ci:with-real-wallet
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-earn-protocol-with-real-wallet
          path: playwright-reports/earn-protocol-with-real-wallet
          retention-days: 30
