name: Reusable Workflow - Regression - No wallet

on: 
  workflow_call:
    inputs:
      base_url:
        description: 'Environment base URL to run the tests on.'
        type: string
        default: 'https://staging.summer.fi'
        required: true
      flags_features:
        description: 'Features Flags to enable / disable. For example: "flag1:true flag2:false"'
        type: string
        default: ''
        required: false

jobs:
  no-wallet-tests:
    name: 'No wallet'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.37.1-jammy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Run NO-WALLET tests
        run: BASE_URL=${{ inputs.base_url }} FLAGS_FEATURES=${{ inputs.flags_features}} yarn ci:no-wallet:regression
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-no-wallet
          path: playwright-reports/no-wallet
          retention-days: 30
